---
name: "RestApi theme"
author: "maxime constantinian"
copyright: "Ambroise Maupate, Julien Blanchet"
themeDir: "RestApiTheme"
supportedLocale:
    - "en"
    - "fr"
versionRequire: "0.7"
importFiles:
    roles: []
    groups: []
    settings: []
    nodetypes: []
    tags: []
    nodes: []
