defaultRemoveTrailingSlash:
    path: /{url}
    defaults:
        _controller: Themes\RestApiTheme\RestApiThemeApp::removeTrailingSlashAction
    requirements:
        url: .*/$
    methods: [GET]

authorizeApiPage:
    path: /oauth
    defaults:
        _controller: Themes\RestApiTheme\Controllers\AuthController::oauthAction

signInPage:
    path: /signin
    defaults:
        _controller: Themes\RestApiTheme\Controllers\ApiLoginController::indexAction

authorizeScopePage:
    path: /authorize
    methods:
        - GET
        - POST
    defaults:
        _controller: Themes\RestApiTheme\Controllers\AuthController::authorizeAction

tokenInfoPage:
    path: /token
    methods:
        - GET
    defaults:
        _controller: Themes\RestApiTheme\Controllers\TokenInfoController::defaultAction

tokenCreationPage:
    path: /token
    methods:
        - POST
    defaults:
        _controller: Themes\RestApiTheme\Controllers\AuthController::accessTokenAction
