# This route is required!
clientAdminListPage:
    path:     /rz-admin/api/client
    defaults: { _controller: Themes\RestApiTheme\AdminControllers\ClientController::listAction }

defaultRemoveTrailingSlash:
    path: /{url}
    defaults: { _controller: Themes\RestApiTheme\RestApiThemeApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]
