defaultRemoveTrailingSlash:
    path: /{url}
    defaults: { _controller: Themes\RestApiTheme\RestApiThemeApp::removeTrailingSlashAction }
    requirements:
        url: .*/$
    methods: [GET]

authorizeApiPage:
    path: /oauth
    defaults: { _controller: Themes\RestApiTheme\Controllers\AuthController::oauthAction}

signInPage:
    path: /signin
    defaults: { _controller: Themes\RestApiTheme\Controllers\ApiLoginController::indexAction}

authorizeScopePage:
    path: /authorize
    defaults: { _controller: Themes\RestApiTheme\Controllers\AuthController::authorizeAction}

accessTokenPage:
    path: /access_token
    methods:
      - POST
    defaults: { _controller: Themes\RestApiTheme\Controllers\AuthController::accessTokenAction}
